version: '3.7'

services:
  web:
    container_name: todolistApi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: donaldwu
      POSTGRES_PASSWORD: donaldwu
      POSTGRES_DB: donaldwu