version: '3.7'

services:
  web:
    container_name: todolistApi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:12.1
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: donaldwu
      POSTGRES_PASSWORD: donaldwu
      POSTGRES_DB: donaldwu